FROM golang:1.24-alpine AS builder
WORKDIR /src
RUN apk add --no-cache wget

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/feature-flag .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /out/feature-flag ./feature-flag 
EXPOSE 8080
ENTRYPOINT ["./feature-flag"]